Fix for AbstractNavigationFactory.php
I think it's a common use case for the default navigation, to add pages and sub pages across many modules.
There's currently an issue when adding sub pages to another page that you expect to be in configuration already.
The main page could be changed to another name, could be removed or the module could be disabled inside an application architecture that uses ZF2 modules like plug-ins.

What happens in this case?

-------------------------------------------------------------
Fatal error: Uncaught exception 'Zend\Navigation\Exception\InvalidArgumentException' with message 'Invalid argument: Unable to determine class to instantiate' in /var/www/html/ebonikerp/vendor/zendframework/zendframework/library/Zend/Navigation/Page/AbstractPage.php:254 Stack trace: #0 /var/www/html/ebonikerp/vendor/zendframework/zendframework/library/Zend/Navigation/AbstractContainer.php(114): Zend\Navigation\Page\AbstractPage::factory(Array) #1 /var/www/html/ebonikerp/vendor/zendframework/zendframework/library/Zend/Navigation/AbstractContainer.php(165): Zend\Navigation\AbstractContainer->addPage(Array) #2 /var/www/html/ebonikerp/vendor/zendframework/zendframework/library/Zend/Navigation/Navigation.php(35): Zend\Navigation\AbstractContainer->addPages(Array) #3 /var/www/html/ebonikerp/vendor/zendframework/zendframework/library/Zend/Navigation/Service/AbstractNavigationFactory.php(38): Zend\Navigation\Navigation->__construct(Array) #4 [internal function]: Zend\Navigation\Service\AbstractNavigationFactory->createService(Obj in /var/www/html/ebonikerp/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 946
-------------------------------------------------------------

This fix solves the problem, by ignoring a main page, when it's missing uri or mvc values, and could be used as quick fix.

For future I would like to see a validation for the pages configs, before they're being injected to navigation.
Another approach could be to add a separate "navigation-extension" configuration beside the "navigation" configuration. The "navigation-extension" configuration could be used to extend the navigation safely. The NavigationFactory would then use only the configuration parts that already have a valid existing navigation entry inside "navigation" key.